#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:/Users/knuterikborgen/Documents/workspacephp/gwt-mac-1.4.61/gwt-user.jar:/Users/knuterikborgen/Documents/workspacephp/gwt-mac-1.4.61/gwt-dev-mac.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" no.knubo.bok.BokGWT/BokGWT.html;
