#!/bin/sh
APPDIR=`dirname $0`;

GWT_ROOT='/Users/knuterikborgen/Documents/workspacephp/gwt-mac-0.0.2415'
CP="$APPDIR/src:$APPDIR/bin:$GWT_ROOT/gwt-user.jar:$GWT_ROOT/gwt-dev-mac.jar"


java -XstartOnFirstThread -cp "$CP" com.google.gwt.dev.GWTShell -noserver -whitelist "^http[:][/][/]localhost" -out "$APPDIR/www" "$@" http://localhost/BokClient/www/no.knubo.bok.BokGWT/BokGWT.html
